Pcc26 (#55)
* init solution

* add requirements

* almost done: matplotlib stats, but getting
_tkinter.TclError: image pyimage doesn't exist

* added launcher

* pomodoro script done

* added readme / printscreens

* small edits readme