Pcc26 - simplified addition (no matplotlib) and executable (#56)
* init solution

* add requirements

* almost done: matplotlib stats, but getting
_tkinter.TclError: image pyimage doesn't exist

* added launcher

* pomodoro script done

* added readme / printscreens

* small edits readme

* added executable

* added executable of simplified version ("simple" branch) - this one does not rely on matplotlib being installed

* the no matplotlib version